# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syringe_pump_controller_ui.ui'
#
# Created: Tue Aug 12 16:39:57 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.motor_select_pane = QtWidgets.QWidget(self.centralwidget)
        self.motor_select_pane.setMinimumSize(QtCore.QSize(0, 24))
        self.motor_select_pane.setMaximumSize(QtCore.QSize(16777215, 32))
        self.motor_select_pane.setObjectName("motor_select_pane")
        self.verticalLayout.addWidget(self.motor_select_pane)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 256))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.injection_tab = QtWidgets.QWidget()
        self.injection_tab.setObjectName("injection_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.injection_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.injection_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.injection_vol_unit = QtWidgets.QComboBox(self.injection_tab)
        self.injection_vol_unit.setObjectName("injection_vol_unit")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.gridLayout.addWidget(self.injection_vol_unit, 0, 1, 1, 1)
        self.injection_time_unit = QtWidgets.QComboBox(self.injection_tab)
        self.injection_time_unit.setObjectName("injection_time_unit")
        self.injection_time_unit.addItem("")
        self.injection_time_unit.addItem("")
        self.injection_time_unit.addItem("")
        self.gridLayout.addWidget(self.injection_time_unit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.injection_tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inject_amount_num = QtWidgets.QLineEdit(self.injection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inject_amount_num.sizePolicy().hasHeightForWidth())
        self.inject_amount_num.setSizePolicy(sizePolicy)
        self.inject_amount_num.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inject_amount_num.setObjectName("inject_amount_num")
        self.gridLayout.addWidget(self.inject_amount_num, 0, 2, 1, 1)
        self.inject_time_num = QtWidgets.QLineEdit(self.injection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inject_time_num.sizePolicy().hasHeightForWidth())
        self.inject_time_num.setSizePolicy(sizePolicy)
        self.inject_time_num.setObjectName("inject_time_num")
        self.gridLayout.addWidget(self.inject_time_num, 1, 2, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.inject_button = QtWidgets.QPushButton(self.injection_tab)
        self.inject_button.setObjectName("inject_button")
        self.horizontalLayout.addWidget(self.inject_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.injection_tab, "")
        self.pumpin_tab = QtWidgets.QWidget()
        self.pumpin_tab.setObjectName("pumpin_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pumpin_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.pumping_vol_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_vol_num.setObjectName("pumping_vol_num")
        self.gridLayout_4.addWidget(self.pumping_vol_num, 0, 2, 1, 1)
        self.pumping_vol_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_vol_unit.setObjectName("pumping_vol_unit")
        self.pumping_vol_unit.addItem("")
        self.gridLayout_4.addWidget(self.pumping_vol_unit, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pumping_bottom_wait_time_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_bottom_wait_time_num.setObjectName("pumping_bottom_wait_time_num")
        self.gridLayout_5.addWidget(self.pumping_bottom_wait_time_num, 4, 2, 1, 1)
        self.pumping_push_time_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_push_time_num.setObjectName("pumping_push_time_num")
        self.gridLayout_5.addWidget(self.pumping_push_time_num, 3, 2, 1, 1)
        self.pumping_top_wait_time_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_top_wait_time_num.setObjectName("pumping_top_wait_time_num")
        self.gridLayout_5.addWidget(self.pumping_top_wait_time_num, 2, 2, 1, 1)
        self.pumping_pumps_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_pumps_num.setObjectName("pumping_pumps_num")
        self.gridLayout_5.addWidget(self.pumping_pumps_num, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.pumping_bottom_wait_time_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_bottom_wait_time_unit.setObjectName("pumping_bottom_wait_time_unit")
        self.pumping_bottom_wait_time_unit.addItem("")
        self.pumping_bottom_wait_time_unit.addItem("")
        self.pumping_bottom_wait_time_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_bottom_wait_time_unit, 4, 1, 1, 1)
        self.pumping_push_time_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_push_time_unit.setObjectName("pumping_push_time_unit")
        self.pumping_push_time_unit.addItem("")
        self.pumping_push_time_unit.addItem("")
        self.pumping_push_time_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_push_time_unit, 3, 1, 1, 1)
        self.pumping_top_wait_time_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_top_wait_time_unit.setObjectName("pumping_top_wait_time_unit")
        self.pumping_top_wait_time_unit.addItem("")
        self.pumping_top_wait_time_unit.addItem("")
        self.pumping_top_wait_time_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_top_wait_time_unit, 2, 1, 1, 1)
        self.pumping_pumps_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_pumps_unit.setObjectName("pumping_pumps_unit")
        self.pumping_pumps_unit.addItem("")
        self.pumping_pumps_unit.addItem("")
        self.pumping_pumps_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_pumps_unit, 0, 1, 1, 1)
        self.pumping_pull_time_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_pull_time_unit.setObjectName("pumping_pull_time_unit")
        self.pumping_pull_time_unit.addItem("")
        self.pumping_pull_time_unit.addItem("")
        self.pumping_pull_time_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_pull_time_unit, 1, 1, 1, 1)
        self.pumping_pull_time_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_pull_time_num.setObjectName("pumping_pull_time_num")
        self.gridLayout_5.addWidget(self.pumping_pull_time_num, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.pump_button = QtWidgets.QPushButton(self.pumpin_tab)
        self.pump_button.setObjectName("pump_button")
        self.horizontalLayout_2.addWidget(self.pump_button)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.pumpin_tab, "")
        self.calibration_tab = QtWidgets.QWidget()
        self.calibration_tab.setObjectName("calibration_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.calibration_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.calibration_tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.calib_ml_per_rad_line = QtWidgets.QLineEdit(self.calibration_tab)
        self.calib_ml_per_rad_line.setObjectName("calib_ml_per_rad_line")
        self.horizontalLayout_4.addWidget(self.calib_ml_per_rad_line)
        self.label_15 = QtWidgets.QLabel(self.calibration_tab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.calib_pos_per_rad_line = QtWidgets.QLineEdit(self.calibration_tab)
        self.calib_pos_per_rad_line.setObjectName("calib_pos_per_rad_line")
        self.horizontalLayout_4.addWidget(self.calib_pos_per_rad_line)
        self.calib_default_radio = QtWidgets.QRadioButton(self.calibration_tab)
        self.calib_default_radio.setEnabled(True)
        self.calib_default_radio.setCheckable(True)
        self.calib_default_radio.setChecked(True)
        self.calib_default_radio.setObjectName("calib_default_radio")
        self.horizontalLayout_4.addWidget(self.calib_default_radio)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_13 = QtWidgets.QLabel(self.calibration_tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.act_vol_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.act_vol_unit.setObjectName("act_vol_unit")
        self.act_vol_unit.addItem("")
        self.gridLayout_6.addWidget(self.act_vol_unit, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.calibration_tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.act_rot_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.act_rot_unit.setObjectName("act_rot_unit")
        self.act_rot_unit.addItem("")
        self.act_rot_unit.addItem("")
        self.act_rot_unit.addItem("")
        self.gridLayout_6.addWidget(self.act_rot_unit, 1, 1, 1, 1)
        self.act_vol_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.act_vol_num.setObjectName("act_vol_num")
        self.gridLayout_6.addWidget(self.act_vol_num, 0, 2, 1, 1)
        self.act_rot_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.act_rot_num.setObjectName("act_rot_num")
        self.gridLayout_6.addWidget(self.act_rot_num, 1, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cal_by_rot_radio = QtWidgets.QRadioButton(self.calibration_tab)
        self.cal_by_rot_radio.setText("")
        self.cal_by_rot_radio.setObjectName("cal_by_rot_radio")
        self.gridLayout_3.addWidget(self.cal_by_rot_radio, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.calibration_tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 1, 1, 1)
        self.cal_by_vol_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.cal_by_vol_unit.setObjectName("cal_by_vol_unit")
        self.cal_by_vol_unit.addItem("")
        self.gridLayout_3.addWidget(self.cal_by_vol_unit, 1, 2, 1, 1)
        self.cal_by_vol_radio = QtWidgets.QRadioButton(self.calibration_tab)
        self.cal_by_vol_radio.setText("")
        self.cal_by_vol_radio.setObjectName("cal_by_vol_radio")
        self.gridLayout_3.addWidget(self.cal_by_vol_radio, 1, 0, 1, 1)
        self.cal_by_rot_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.cal_by_rot_unit.setObjectName("cal_by_rot_unit")
        self.cal_by_rot_unit.addItem("")
        self.cal_by_rot_unit.addItem("")
        self.cal_by_rot_unit.addItem("")
        self.gridLayout_3.addWidget(self.cal_by_rot_unit, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.calibration_tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 1, 1, 1)
        self.cal_by_vol_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.cal_by_vol_num.setObjectName("cal_by_vol_num")
        self.gridLayout_3.addWidget(self.cal_by_vol_num, 1, 3, 1, 1)
        self.cal_by_rot_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.cal_by_rot_num.setObjectName("cal_by_rot_num")
        self.gridLayout_3.addWidget(self.cal_by_rot_num, 2, 3, 1, 1)
        self.cal_time_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.cal_time_num.setObjectName("cal_time_num")
        self.gridLayout_3.addWidget(self.cal_time_num, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.calibration_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.cal_time_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.cal_time_unit.setObjectName("cal_time_unit")
        self.cal_time_unit.addItem("")
        self.gridLayout_3.addWidget(self.cal_time_unit, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.calibrate_pump_button = QtWidgets.QPushButton(self.calibration_tab)
        self.calibrate_pump_button.setObjectName("calibrate_pump_button")
        self.horizontalLayout_3.addWidget(self.calibrate_pump_button)
        self.calibrate_button = QtWidgets.QPushButton(self.calibration_tab)
        self.calibrate_button.setObjectName("calibrate_button")
        self.horizontalLayout_3.addWidget(self.calibrate_button)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.calibration_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.command_and_stop_pane = QtWidgets.QWidget(self.centralwidget)
        self.command_and_stop_pane.setMinimumSize(QtCore.QSize(0, 64))
        self.command_and_stop_pane.setObjectName("command_and_stop_pane")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.command_and_stop_pane)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.RUN = QtWidgets.QPushButton(self.command_and_stop_pane)
        self.RUN.setObjectName("RUN")
        self.verticalLayout_6.addWidget(self.RUN)
        self.STOP = QtWidgets.QPushButton(self.command_and_stop_pane)
        self.STOP.setObjectName("STOP")
        self.verticalLayout_6.addWidget(self.STOP)
        self.Reset_0_button = QtWidgets.QPushButton(self.command_and_stop_pane)
        self.Reset_0_button.setObjectName("Reset_0_button")
        self.verticalLayout_6.addWidget(self.Reset_0_button)
        self.Revers_button = QtWidgets.QPushButton(self.command_and_stop_pane)
        self.Revers_button.setObjectName("Revers_button")
        self.verticalLayout_6.addWidget(self.Revers_button)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.console = QtWidgets.QPlainTextEdit(self.command_and_stop_pane)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.console.setPalette(palette)
        self.console.setPlainText("")
        self.console.setBackgroundVisible(False)
        self.console.setObjectName("console")
        self.verticalLayout_5.addWidget(self.console)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.command_and_stop_pane)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Time"))
        self.injection_vol_unit.setItemText(0, _translate("MainWindow", "cc"))
        self.injection_vol_unit.setItemText(1, _translate("MainWindow", "mL"))
        self.injection_vol_unit.setItemText(2, _translate("MainWindow", "L"))
        self.injection_vol_unit.setItemText(3, _translate("MainWindow", "Gallons"))
        self.injection_vol_unit.setItemText(4, _translate("MainWindow", "Pints"))
        self.injection_vol_unit.setItemText(5, _translate("MainWindow", "teaspoons"))
        self.injection_vol_unit.setItemText(6, _translate("MainWindow", "Buckets"))
        self.injection_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.injection_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.injection_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.label.setText(_translate("MainWindow", "Amount:"))
        self.inject_button.setText(_translate("MainWindow", "Inject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.injection_tab), _translate("MainWindow", "Injection"))
        self.label_5.setText(_translate("MainWindow", "volume"))
        self.pumping_vol_unit.setItemText(0, _translate("MainWindow", "mL"))
        self.label_10.setText(_translate("MainWindow", "No. of pumps"))
        self.pumping_bottom_wait_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.pumping_bottom_wait_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.pumping_bottom_wait_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.pumping_push_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.pumping_push_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.pumping_push_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.pumping_top_wait_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.pumping_top_wait_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.pumping_top_wait_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.pumping_pumps_unit.setItemText(0, _translate("MainWindow", "num"))
        self.pumping_pumps_unit.setItemText(1, _translate("MainWindow", "K"))
        self.pumping_pumps_unit.setItemText(2, _translate("MainWindow", "M"))
        self.pumping_pull_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.pumping_pull_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.pumping_pull_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.label_4.setText(_translate("MainWindow", "Pull time"))
        self.label_8.setText(_translate("MainWindow", "Bottom wait time"))
        self.label_9.setText(_translate("MainWindow", "Push time"))
        self.label_7.setText(_translate("MainWindow", "Top wait time"))
        self.pump_button.setText(_translate("MainWindow", "Pump"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pumpin_tab), _translate("MainWindow", "Pumping"))
        self.label_6.setText(_translate("MainWindow", "mL_per_rad"))
        self.label_15.setText(_translate("MainWindow", "pos_per_rad"))
        self.calib_default_radio.setText(_translate("MainWindow", "Default?"))
        self.label_13.setText(_translate("MainWindow", "Actual volume"))
        self.act_vol_unit.setItemText(0, _translate("MainWindow", "mL"))
        self.label_14.setText(_translate("MainWindow", "Actual rotations"))
        self.act_rot_unit.setItemText(0, _translate("MainWindow", "°"))
        self.act_rot_unit.setItemText(1, _translate("MainWindow", "θ"))
        self.act_rot_unit.setItemText(2, _translate("MainWindow", "no. rev."))
        self.label_12.setText(_translate("MainWindow", "Rotations"))
        self.cal_by_vol_unit.setItemText(0, _translate("MainWindow", "mL"))
        self.cal_by_rot_unit.setItemText(0, _translate("MainWindow", "°"))
        self.cal_by_rot_unit.setItemText(1, _translate("MainWindow", "θ"))
        self.cal_by_rot_unit.setItemText(2, _translate("MainWindow", "no. rev."))
        self.label_11.setText(_translate("MainWindow", "Test volume"))
        self.label_3.setText(_translate("MainWindow", "Time"))
        self.cal_time_unit.setItemText(0, _translate("MainWindow", "sec"))
        self.calibrate_pump_button.setText(_translate("MainWindow", "Pump"))
        self.calibrate_button.setText(_translate("MainWindow", "Calibrate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibration_tab), _translate("MainWindow", "Calibration"))
        self.RUN.setText(_translate("MainWindow", "RUN"))
        self.STOP.setText(_translate("MainWindow", "STOP"))
        self.Reset_0_button.setText(_translate("MainWindow", "Reset 0"))
        self.Revers_button.setText(_translate("MainWindow", "Reverse"))

