# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syringe_pump_controller_ui.ui'
#
# Created: Mon Aug 18 16:55:13 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(695, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setMaximumSize(QtCore.QSize(16777215, 256))
        self.tabs.setTabsClosable(False)
        self.tabs.setObjectName("tabs")
        self.injection_tab = QtWidgets.QWidget()
        self.injection_tab.setObjectName("injection_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.injection_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.injection_tab)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(self.injection_tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 1)
        self.max_inject_i = QtWidgets.QLineEdit(self.injection_tab)
        self.max_inject_i.setEnabled(False)
        self.max_inject_i.setObjectName("max_inject_i")
        self.gridLayout_11.addWidget(self.max_inject_i, 0, 1, 1, 1)
        self.max_draw_i = QtWidgets.QLineEdit(self.injection_tab)
        self.max_draw_i.setEnabled(False)
        self.max_draw_i.setObjectName("max_draw_i")
        self.gridLayout_11.addWidget(self.max_draw_i, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.injection_tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.injection_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.injection_vol_unit = QtWidgets.QComboBox(self.injection_tab)
        self.injection_vol_unit.setObjectName("injection_vol_unit")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.injection_vol_unit.addItem("")
        self.gridLayout.addWidget(self.injection_vol_unit, 0, 1, 1, 1)
        self.injection_time_unit = QtWidgets.QComboBox(self.injection_tab)
        self.injection_time_unit.setObjectName("injection_time_unit")
        self.injection_time_unit.addItem("")
        self.injection_time_unit.addItem("")
        self.injection_time_unit.addItem("")
        self.gridLayout.addWidget(self.injection_time_unit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.injection_tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inject_amount_num = QtWidgets.QLineEdit(self.injection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inject_amount_num.sizePolicy().hasHeightForWidth())
        self.inject_amount_num.setSizePolicy(sizePolicy)
        self.inject_amount_num.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inject_amount_num.setObjectName("inject_amount_num")
        self.gridLayout.addWidget(self.inject_amount_num, 0, 2, 1, 1)
        self.inject_time_num = QtWidgets.QLineEdit(self.injection_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inject_time_num.sizePolicy().hasHeightForWidth())
        self.inject_time_num.setSizePolicy(sizePolicy)
        self.inject_time_num.setObjectName("inject_time_num")
        self.gridLayout.addWidget(self.inject_time_num, 1, 2, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.inject_button = QtWidgets.QPushButton(self.injection_tab)
        self.inject_button.setObjectName("inject_button")
        self.horizontalLayout.addWidget(self.inject_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabs.addTab(self.injection_tab, "")
        self.pumpin_tab = QtWidgets.QWidget()
        self.pumpin_tab.setObjectName("pumpin_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pumpin_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_21 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.max_draw_p = QtWidgets.QLineEdit(self.pumpin_tab)
        self.max_draw_p.setEnabled(False)
        self.max_draw_p.setObjectName("max_draw_p")
        self.gridLayout_12.addWidget(self.max_draw_p, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_12)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.pumping_vol_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_vol_num.setObjectName("pumping_vol_num")
        self.gridLayout_4.addWidget(self.pumping_vol_num, 0, 2, 1, 1)
        self.pumping_vol_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_vol_unit.setObjectName("pumping_vol_unit")
        self.pumping_vol_unit.addItem("")
        self.gridLayout_4.addWidget(self.pumping_vol_unit, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pumping_bottom_wait_time_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_bottom_wait_time_num.setObjectName("pumping_bottom_wait_time_num")
        self.gridLayout_5.addWidget(self.pumping_bottom_wait_time_num, 4, 2, 1, 1)
        self.pumping_push_time_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_push_time_num.setObjectName("pumping_push_time_num")
        self.gridLayout_5.addWidget(self.pumping_push_time_num, 3, 2, 1, 1)
        self.pumping_top_wait_time_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_top_wait_time_num.setObjectName("pumping_top_wait_time_num")
        self.gridLayout_5.addWidget(self.pumping_top_wait_time_num, 2, 2, 1, 1)
        self.pumping_pumps_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_pumps_num.setObjectName("pumping_pumps_num")
        self.gridLayout_5.addWidget(self.pumping_pumps_num, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.pumping_bottom_wait_time_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_bottom_wait_time_unit.setObjectName("pumping_bottom_wait_time_unit")
        self.pumping_bottom_wait_time_unit.addItem("")
        self.pumping_bottom_wait_time_unit.addItem("")
        self.pumping_bottom_wait_time_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_bottom_wait_time_unit, 4, 1, 1, 1)
        self.pumping_push_time_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_push_time_unit.setObjectName("pumping_push_time_unit")
        self.pumping_push_time_unit.addItem("")
        self.pumping_push_time_unit.addItem("")
        self.pumping_push_time_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_push_time_unit, 3, 1, 1, 1)
        self.pumping_top_wait_time_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_top_wait_time_unit.setObjectName("pumping_top_wait_time_unit")
        self.pumping_top_wait_time_unit.addItem("")
        self.pumping_top_wait_time_unit.addItem("")
        self.pumping_top_wait_time_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_top_wait_time_unit, 2, 1, 1, 1)
        self.pumping_pumps_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_pumps_unit.setObjectName("pumping_pumps_unit")
        self.pumping_pumps_unit.addItem("")
        self.pumping_pumps_unit.addItem("")
        self.pumping_pumps_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_pumps_unit, 0, 1, 1, 1)
        self.pumping_pull_time_unit = QtWidgets.QComboBox(self.pumpin_tab)
        self.pumping_pull_time_unit.setObjectName("pumping_pull_time_unit")
        self.pumping_pull_time_unit.addItem("")
        self.pumping_pull_time_unit.addItem("")
        self.pumping_pull_time_unit.addItem("")
        self.gridLayout_5.addWidget(self.pumping_pull_time_unit, 1, 1, 1, 1)
        self.pumping_pull_time_num = QtWidgets.QLineEdit(self.pumpin_tab)
        self.pumping_pull_time_num.setObjectName("pumping_pull_time_num")
        self.gridLayout_5.addWidget(self.pumping_pull_time_num, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.pumpin_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.pump_button = QtWidgets.QPushButton(self.pumpin_tab)
        self.pump_button.setObjectName("pump_button")
        self.horizontalLayout_2.addWidget(self.pump_button)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabs.addTab(self.pumpin_tab, "")
        self.calibration_tab = QtWidgets.QWidget()
        self.calibration_tab.setObjectName("calibration_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.calibration_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.calibration_tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.calib_ml_per_rad_line = QtWidgets.QLineEdit(self.calibration_tab)
        self.calib_ml_per_rad_line.setEnabled(False)
        self.calib_ml_per_rad_line.setObjectName("calib_ml_per_rad_line")
        self.horizontalLayout_4.addWidget(self.calib_ml_per_rad_line)
        self.label_15 = QtWidgets.QLabel(self.calibration_tab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.calib_pos_per_rad_line = QtWidgets.QLineEdit(self.calibration_tab)
        self.calib_pos_per_rad_line.setEnabled(False)
        self.calib_pos_per_rad_line.setObjectName("calib_pos_per_rad_line")
        self.horizontalLayout_4.addWidget(self.calib_pos_per_rad_line)
        self.calib_default_radio = QtWidgets.QCheckBox(self.calibration_tab)
        self.calib_default_radio.setEnabled(False)
        self.calib_default_radio.setCheckable(True)
        self.calib_default_radio.setChecked(True)
        self.calib_default_radio.setObjectName("calib_default_radio")
        self.horizontalLayout_4.addWidget(self.calib_default_radio)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.max_inject_c = QtWidgets.QLineEdit(self.calibration_tab)
        self.max_inject_c.setEnabled(False)
        self.max_inject_c.setObjectName("max_inject_c")
        self.gridLayout_13.addWidget(self.max_inject_c, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.calibration_tab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 1, 0, 1, 1)
        self.max_draw_c = QtWidgets.QLineEdit(self.calibration_tab)
        self.max_draw_c.setEnabled(False)
        self.max_draw_c.setObjectName("max_draw_c")
        self.gridLayout_13.addWidget(self.max_draw_c, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.calibration_tab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_13)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_13 = QtWidgets.QLabel(self.calibration_tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.act_vol_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.act_vol_unit.setEnabled(False)
        self.act_vol_unit.setObjectName("act_vol_unit")
        self.act_vol_unit.addItem("")
        self.gridLayout_6.addWidget(self.act_vol_unit, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.calibration_tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.act_rot_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.act_rot_unit.setEnabled(False)
        self.act_rot_unit.setObjectName("act_rot_unit")
        self.act_rot_unit.addItem("")
        self.act_rot_unit.addItem("")
        self.act_rot_unit.addItem("")
        self.gridLayout_6.addWidget(self.act_rot_unit, 1, 1, 1, 1)
        self.act_vol_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.act_vol_num.setEnabled(False)
        self.act_vol_num.setObjectName("act_vol_num")
        self.gridLayout_6.addWidget(self.act_vol_num, 0, 2, 1, 1)
        self.act_rot_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.act_rot_num.setEnabled(False)
        self.act_rot_num.setObjectName("act_rot_num")
        self.gridLayout_6.addWidget(self.act_rot_num, 1, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cal_by_rot_radio = QtWidgets.QRadioButton(self.calibration_tab)
        self.cal_by_rot_radio.setText("")
        self.cal_by_rot_radio.setObjectName("cal_by_rot_radio")
        self.gridLayout_3.addWidget(self.cal_by_rot_radio, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.calibration_tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 1, 1, 1)
        self.cal_by_vol_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.cal_by_vol_unit.setEnabled(False)
        self.cal_by_vol_unit.setEditable(False)
        self.cal_by_vol_unit.setObjectName("cal_by_vol_unit")
        self.cal_by_vol_unit.addItem("")
        self.gridLayout_3.addWidget(self.cal_by_vol_unit, 1, 2, 1, 1)
        self.cal_by_vol_radio = QtWidgets.QRadioButton(self.calibration_tab)
        self.cal_by_vol_radio.setText("")
        self.cal_by_vol_radio.setObjectName("cal_by_vol_radio")
        self.gridLayout_3.addWidget(self.cal_by_vol_radio, 1, 0, 1, 1)
        self.cal_by_rot_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.cal_by_rot_unit.setEnabled(False)
        self.cal_by_rot_unit.setObjectName("cal_by_rot_unit")
        self.cal_by_rot_unit.addItem("")
        self.cal_by_rot_unit.addItem("")
        self.cal_by_rot_unit.addItem("")
        self.gridLayout_3.addWidget(self.cal_by_rot_unit, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.calibration_tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 1, 1, 1)
        self.cal_by_vol_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.cal_by_vol_num.setEnabled(False)
        self.cal_by_vol_num.setObjectName("cal_by_vol_num")
        self.gridLayout_3.addWidget(self.cal_by_vol_num, 1, 3, 1, 1)
        self.cal_by_rot_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.cal_by_rot_num.setEnabled(False)
        self.cal_by_rot_num.setObjectName("cal_by_rot_num")
        self.gridLayout_3.addWidget(self.cal_by_rot_num, 2, 3, 1, 1)
        self.cal_time_num = QtWidgets.QLineEdit(self.calibration_tab)
        self.cal_time_num.setObjectName("cal_time_num")
        self.gridLayout_3.addWidget(self.cal_time_num, 0, 3, 1, 1)
        self.cal_time_unit = QtWidgets.QComboBox(self.calibration_tab)
        self.cal_time_unit.setObjectName("cal_time_unit")
        self.cal_time_unit.addItem("")
        self.gridLayout_3.addWidget(self.cal_time_unit, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.calibration_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_7)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.calibrate_pump_button = QtWidgets.QPushButton(self.calibration_tab)
        self.calibrate_pump_button.setObjectName("calibrate_pump_button")
        self.horizontalLayout_3.addWidget(self.calibrate_pump_button)
        self.calibrate_button = QtWidgets.QPushButton(self.calibration_tab)
        self.calibrate_button.setObjectName("calibrate_button")
        self.horizontalLayout_3.addWidget(self.calibrate_button)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabs.addTab(self.calibration_tab, "")
        self.verticalLayout.addWidget(self.tabs)
        self.command_and_stop_pane = QtWidgets.QWidget(self.centralwidget)
        self.command_and_stop_pane.setMinimumSize(QtCore.QSize(0, 64))
        self.command_and_stop_pane.setObjectName("command_and_stop_pane")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.command_and_stop_pane)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pump_select = QtWidgets.QComboBox(self.command_and_stop_pane)
        self.pump_select.setObjectName("pump_select")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.verticalLayout_7.addWidget(self.pump_select)
        self.check_status_button = QtWidgets.QPushButton(self.command_and_stop_pane)
        self.check_status_button.setObjectName("check_status_button")
        self.verticalLayout_7.addWidget(self.check_status_button)
        self.check_velocity_button = QtWidgets.QPushButton(self.command_and_stop_pane)
        self.check_velocity_button.setObjectName("check_velocity_button")
        self.verticalLayout_7.addWidget(self.check_velocity_button)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.RUN = QtWidgets.QPushButton(self.command_and_stop_pane)
        self.RUN.setObjectName("RUN")
        self.verticalLayout_6.addWidget(self.RUN)
        self.STOP = QtWidgets.QPushButton(self.command_and_stop_pane)
        self.STOP.setObjectName("STOP")
        self.verticalLayout_6.addWidget(self.STOP)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.set_min_button = QtWidgets.QCheckBox(self.command_and_stop_pane)
        self.set_min_button.setAutoExclusive(False)
        self.set_min_button.setObjectName("set_min_button")
        self.horizontalLayout_13.addWidget(self.set_min_button)
        self.no_min_button = QtWidgets.QCheckBox(self.command_and_stop_pane)
        self.no_min_button.setChecked(True)
        self.no_min_button.setAutoExclusive(False)
        self.no_min_button.setObjectName("no_min_button")
        self.horizontalLayout_13.addWidget(self.no_min_button)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.set_max_button = QtWidgets.QCheckBox(self.command_and_stop_pane)
        self.set_max_button.setAutoExclusive(False)
        self.set_max_button.setObjectName("set_max_button")
        self.horizontalLayout_11.addWidget(self.set_max_button)
        self.no_max_button = QtWidgets.QCheckBox(self.command_and_stop_pane)
        self.no_max_button.setChecked(True)
        self.no_max_button.setAutoExclusive(False)
        self.no_max_button.setObjectName("no_max_button")
        self.horizontalLayout_11.addWidget(self.no_max_button)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.verticalLayout_6.addLayout(self.verticalLayout_11)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.console = QtWidgets.QPlainTextEdit(self.command_and_stop_pane)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.console.setPalette(palette)
        self.console.setPlainText("")
        self.console.setBackgroundVisible(False)
        self.console.setObjectName("console")
        self.verticalLayout_5.addWidget(self.console)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.command_and_stop_pane)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Best Syringe Pump UI"))
        self.label_16.setText(_translate("MainWindow", "Usage: Positive values will inject, negative values will draw."))
        self.label_19.setText(_translate("MainWindow", "Max inject (mL):"))
        self.label_20.setText(_translate("MainWindow", "Max draw (mL):"))
        self.label_2.setText(_translate("MainWindow", "Time"))
        self.injection_vol_unit.setItemText(0, _translate("MainWindow", "cc"))
        self.injection_vol_unit.setItemText(1, _translate("MainWindow", "mL"))
        self.injection_vol_unit.setItemText(2, _translate("MainWindow", "L"))
        self.injection_vol_unit.setItemText(3, _translate("MainWindow", "Gallons"))
        self.injection_vol_unit.setItemText(4, _translate("MainWindow", "Pints"))
        self.injection_vol_unit.setItemText(5, _translate("MainWindow", "teaspoons"))
        self.injection_vol_unit.setItemText(6, _translate("MainWindow", "Buckets"))
        self.injection_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.injection_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.injection_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.label.setText(_translate("MainWindow", "Amount:"))
        self.inject_button.setText(_translate("MainWindow", "Inject"))
        self.tabs.setTabText(self.tabs.indexOf(self.injection_tab), _translate("MainWindow", "Injection"))
        self.label_17.setText(_translate("MainWindow", "Note: stroke volume indicates both volume drawn and injected.  e.g. 3mL will draw 3mL, then inject 3mL, then repeat."))
        self.label_21.setText(_translate("MainWindow", "Note 2: setting No. of pumps to 0 to loop infinitely"))
        self.label_22.setText(_translate("MainWindow", "Max draw (mL):"))
        self.label_5.setText(_translate("MainWindow", "stroke volume"))
        self.pumping_vol_unit.setItemText(0, _translate("MainWindow", "mL"))
        self.label_10.setText(_translate("MainWindow", "No. of pumps"))
        self.pumping_bottom_wait_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.pumping_bottom_wait_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.pumping_bottom_wait_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.pumping_push_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.pumping_push_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.pumping_push_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.pumping_top_wait_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.pumping_top_wait_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.pumping_top_wait_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.pumping_pumps_unit.setItemText(0, _translate("MainWindow", "num"))
        self.pumping_pumps_unit.setItemText(1, _translate("MainWindow", "K"))
        self.pumping_pumps_unit.setItemText(2, _translate("MainWindow", "M"))
        self.pumping_pull_time_unit.setItemText(0, _translate("MainWindow", "seconds"))
        self.pumping_pull_time_unit.setItemText(1, _translate("MainWindow", "minutes"))
        self.pumping_pull_time_unit.setItemText(2, _translate("MainWindow", "hours"))
        self.label_4.setText(_translate("MainWindow", "Pull time"))
        self.label_8.setText(_translate("MainWindow", "Bottom wait time"))
        self.label_9.setText(_translate("MainWindow", "Push time"))
        self.label_7.setText(_translate("MainWindow", "Top wait time"))
        self.pump_button.setText(_translate("MainWindow", "Pump"))
        self.tabs.setTabText(self.tabs.indexOf(self.pumpin_tab), _translate("MainWindow", "Pumping"))
        self.label_6.setText(_translate("MainWindow", "mL_per_rad"))
        self.label_15.setText(_translate("MainWindow", "pos_per_rad"))
        self.calib_default_radio.setText(_translate("MainWindow", "Default?"))
        self.label_24.setText(_translate("MainWindow", "Max draw (mL):"))
        self.label_23.setText(_translate("MainWindow", "Max inject (mL):"))
        self.label_13.setText(_translate("MainWindow", "Actual volume"))
        self.act_vol_unit.setItemText(0, _translate("MainWindow", "mL"))
        self.label_14.setText(_translate("MainWindow", "Actual rotations"))
        self.act_rot_unit.setItemText(0, _translate("MainWindow", "°"))
        self.act_rot_unit.setItemText(1, _translate("MainWindow", "θ"))
        self.act_rot_unit.setItemText(2, _translate("MainWindow", "no. rev."))
        self.label_12.setText(_translate("MainWindow", "Rotations"))
        self.cal_by_vol_unit.setItemText(0, _translate("MainWindow", "mL"))
        self.cal_by_rot_unit.setItemText(0, _translate("MainWindow", "°"))
        self.cal_by_rot_unit.setItemText(1, _translate("MainWindow", "θ"))
        self.cal_by_rot_unit.setItemText(2, _translate("MainWindow", "no. rev."))
        self.label_11.setText(_translate("MainWindow", "Test volume"))
        self.cal_time_unit.setItemText(0, _translate("MainWindow", "sec"))
        self.label_3.setText(_translate("MainWindow", "Time"))
        self.calibrate_pump_button.setText(_translate("MainWindow", "Pump"))
        self.calibrate_button.setText(_translate("MainWindow", "Calibrate"))
        self.tabs.setTabText(self.tabs.indexOf(self.calibration_tab), _translate("MainWindow", "Calibration"))
        self.pump_select.setItemText(0, _translate("MainWindow", "Pump 1"))
        self.pump_select.setItemText(1, _translate("MainWindow", "Pump 2"))
        self.pump_select.setItemText(2, _translate("MainWindow", "Pump 3"))
        self.pump_select.setItemText(3, _translate("MainWindow", "Pump 4"))
        self.pump_select.setItemText(4, _translate("MainWindow", "Pump 5"))
        self.pump_select.setItemText(5, _translate("MainWindow", "Pump 6"))
        self.pump_select.setItemText(6, _translate("MainWindow", "Pump 7"))
        self.pump_select.setItemText(7, _translate("MainWindow", "Pump 8"))
        self.pump_select.setItemText(8, _translate("MainWindow", "Pump 9"))
        self.pump_select.setItemText(9, _translate("MainWindow", "Pump A"))
        self.pump_select.setItemText(10, _translate("MainWindow", "Pump B"))
        self.pump_select.setItemText(11, _translate("MainWindow", "Pump C"))
        self.pump_select.setItemText(12, _translate("MainWindow", "Pump D"))
        self.pump_select.setItemText(13, _translate("MainWindow", "Pump E"))
        self.pump_select.setItemText(14, _translate("MainWindow", "Pump F"))
        self.pump_select.setItemText(15, _translate("MainWindow", "Pump 0"))
        self.check_status_button.setText(_translate("MainWindow", "Check Status"))
        self.check_velocity_button.setText(_translate("MainWindow", "Check Velocity"))
        self.RUN.setText(_translate("MainWindow", "INITIALIZE"))
        self.STOP.setText(_translate("MainWindow", "STOP"))
        self.set_min_button.setText(_translate("MainWindow", "Set Min Vol"))
        self.no_min_button.setText(_translate("MainWindow", "No Min Vol"))
        self.set_max_button.setText(_translate("MainWindow", "Set Max Vol"))
        self.no_max_button.setText(_translate("MainWindow", "No Max Vol"))

