# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syringe_pump_controller_ui(qt4).ui'
#
# Created: Fri Jun 20 11:17:39 2014
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(693, 457)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.motor_select_pane = QtGui.QWidget(self.centralwidget)
        self.motor_select_pane.setMinimumSize(QtCore.QSize(0, 24))
        self.motor_select_pane.setMaximumSize(QtCore.QSize(16777215, 32))
        self.motor_select_pane.setObjectName(_fromUtf8("motor_select_pane"))
        self.verticalLayout.addWidget(self.motor_select_pane)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 256))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.injection_tab = QtGui.QWidget()
        self.injection_tab.setObjectName(_fromUtf8("injection_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.injection_tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.injection_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.injection_vol_unit = QtGui.QComboBox(self.injection_tab)
        self.injection_vol_unit.setObjectName(_fromUtf8("injection_vol_unit"))
        self.injection_vol_unit.addItem(_fromUtf8(""))
        self.injection_vol_unit.addItem(_fromUtf8(""))
        self.injection_vol_unit.addItem(_fromUtf8(""))
        self.injection_vol_unit.addItem(_fromUtf8(""))
        self.injection_vol_unit.addItem(_fromUtf8(""))
        self.injection_vol_unit.addItem(_fromUtf8(""))
        self.injection_vol_unit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.injection_vol_unit, 0, 1, 1, 1)
        self.injection_time_unit = QtGui.QComboBox(self.injection_tab)
        self.injection_time_unit.setObjectName(_fromUtf8("injection_time_unit"))
        self.injection_time_unit.addItem(_fromUtf8(""))
        self.injection_time_unit.addItem(_fromUtf8(""))
        self.injection_time_unit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.injection_time_unit, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.injection_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inject_amount_num = QtGui.QLineEdit(self.injection_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inject_amount_num.sizePolicy().hasHeightForWidth())
        self.inject_amount_num.setSizePolicy(sizePolicy)
        self.inject_amount_num.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.inject_amount_num.setObjectName(_fromUtf8("inject_amount_num"))
        self.gridLayout.addWidget(self.inject_amount_num, 0, 2, 1, 1)
        self.inject_time_num = QtGui.QLineEdit(self.injection_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inject_time_num.sizePolicy().hasHeightForWidth())
        self.inject_time_num.setSizePolicy(sizePolicy)
        self.inject_time_num.setObjectName(_fromUtf8("inject_time_num"))
        self.gridLayout.addWidget(self.inject_time_num, 1, 2, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.inject_button = QtGui.QPushButton(self.injection_tab)
        self.inject_button.setObjectName(_fromUtf8("inject_button"))
        self.horizontalLayout.addWidget(self.inject_button)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.injection_tab, _fromUtf8(""))
        self.pumpin_tab = QtGui.QWidget()
        self.pumpin_tab.setObjectName(_fromUtf8("pumpin_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pumpin_tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pumping_vol_unit = QtGui.QComboBox(self.pumpin_tab)
        self.pumping_vol_unit.setObjectName(_fromUtf8("pumping_vol_unit"))
        self.pumping_vol_unit.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.pumping_vol_unit, 1, 1, 1, 1)
        self.pumping_vol_num = QtGui.QLineEdit(self.pumpin_tab)
        self.pumping_vol_num.setObjectName(_fromUtf8("pumping_vol_num"))
        self.gridLayout_4.addWidget(self.pumping_vol_num, 1, 2, 1, 1)
        self.pumping_Q_unit = QtGui.QComboBox(self.pumpin_tab)
        self.pumping_Q_unit.setObjectName(_fromUtf8("pumping_Q_unit"))
        self.pumping_Q_unit.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.pumping_Q_unit, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.pumpin_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.pumping_Q_num = QtGui.QLineEdit(self.pumpin_tab)
        self.pumping_Q_num.setObjectName(_fromUtf8("pumping_Q_num"))
        self.gridLayout_4.addWidget(self.pumping_Q_num, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.pumpin_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.pumpin_tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.pumpin_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.pumpin_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.pumpin_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 2, 0, 1, 1)
        self.pumping_pull_time_num = QtGui.QLineEdit(self.pumpin_tab)
        self.pumping_pull_time_num.setObjectName(_fromUtf8("pumping_pull_time_num"))
        self.gridLayout_5.addWidget(self.pumping_pull_time_num, 2, 2, 1, 1)
        self.pumping_pull_time_unit = QtGui.QComboBox(self.pumpin_tab)
        self.pumping_pull_time_unit.setObjectName(_fromUtf8("pumping_pull_time_unit"))
        self.pumping_pull_time_unit.addItem(_fromUtf8(""))
        self.pumping_pull_time_unit.addItem(_fromUtf8(""))
        self.pumping_pull_time_unit.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.pumping_pull_time_unit, 2, 1, 1, 1)
        self.pumping_pumps_unit = QtGui.QComboBox(self.pumpin_tab)
        self.pumping_pumps_unit.setObjectName(_fromUtf8("pumping_pumps_unit"))
        self.pumping_pumps_unit.addItem(_fromUtf8(""))
        self.pumping_pumps_unit.addItem(_fromUtf8(""))
        self.pumping_pumps_unit.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.pumping_pumps_unit, 1, 1, 1, 1)
        self.pumping_top_wait_time_unit = QtGui.QComboBox(self.pumpin_tab)
        self.pumping_top_wait_time_unit.setObjectName(_fromUtf8("pumping_top_wait_time_unit"))
        self.pumping_top_wait_time_unit.addItem(_fromUtf8(""))
        self.pumping_top_wait_time_unit.addItem(_fromUtf8(""))
        self.pumping_top_wait_time_unit.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.pumping_top_wait_time_unit, 3, 1, 1, 1)
        self.pumping_push_time_unit = QtGui.QComboBox(self.pumpin_tab)
        self.pumping_push_time_unit.setObjectName(_fromUtf8("pumping_push_time_unit"))
        self.pumping_push_time_unit.addItem(_fromUtf8(""))
        self.pumping_push_time_unit.addItem(_fromUtf8(""))
        self.pumping_push_time_unit.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.pumping_push_time_unit, 4, 1, 1, 1)
        self.pumping_bottom_wait_time_unit = QtGui.QComboBox(self.pumpin_tab)
        self.pumping_bottom_wait_time_unit.setObjectName(_fromUtf8("pumping_bottom_wait_time_unit"))
        self.pumping_bottom_wait_time_unit.addItem(_fromUtf8(""))
        self.pumping_bottom_wait_time_unit.addItem(_fromUtf8(""))
        self.pumping_bottom_wait_time_unit.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.pumping_bottom_wait_time_unit, 5, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.pumpin_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.pumping_total_time_unit = QtGui.QComboBox(self.pumpin_tab)
        self.pumping_total_time_unit.setObjectName(_fromUtf8("pumping_total_time_unit"))
        self.pumping_total_time_unit.addItem(_fromUtf8(""))
        self.pumping_total_time_unit.addItem(_fromUtf8(""))
        self.pumping_total_time_unit.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.pumping_total_time_unit, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.pumpin_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.pumping_total_time_num = QtGui.QLineEdit(self.pumpin_tab)
        self.pumping_total_time_num.setObjectName(_fromUtf8("pumping_total_time_num"))
        self.gridLayout_5.addWidget(self.pumping_total_time_num, 0, 2, 1, 1)
        self.pumping_pumps_num = QtGui.QLineEdit(self.pumpin_tab)
        self.pumping_pumps_num.setObjectName(_fromUtf8("pumping_pumps_num"))
        self.gridLayout_5.addWidget(self.pumping_pumps_num, 1, 2, 1, 1)
        self.pumping_top_wait_time_num = QtGui.QLineEdit(self.pumpin_tab)
        self.pumping_top_wait_time_num.setObjectName(_fromUtf8("pumping_top_wait_time_num"))
        self.gridLayout_5.addWidget(self.pumping_top_wait_time_num, 3, 2, 1, 1)
        self.pumping_push_time_num = QtGui.QLineEdit(self.pumpin_tab)
        self.pumping_push_time_num.setObjectName(_fromUtf8("pumping_push_time_num"))
        self.gridLayout_5.addWidget(self.pumping_push_time_num, 4, 2, 1, 1)
        self.pumping_bottom_wait_time_num = QtGui.QLineEdit(self.pumpin_tab)
        self.pumping_bottom_wait_time_num.setObjectName(_fromUtf8("pumping_bottom_wait_time_num"))
        self.gridLayout_5.addWidget(self.pumping_bottom_wait_time_num, 5, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.pump_button = QtGui.QPushButton(self.pumpin_tab)
        self.pump_button.setObjectName(_fromUtf8("pump_button"))
        self.horizontalLayout_2.addWidget(self.pump_button)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.pumpin_tab, _fromUtf8(""))
        self.calibration_tab = QtGui.QWidget()
        self.calibration_tab.setObjectName(_fromUtf8("calibration_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.calibration_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_13 = QtGui.QLabel(self.calibration_tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.act_vol_unit = QtGui.QComboBox(self.calibration_tab)
        self.act_vol_unit.setObjectName(_fromUtf8("act_vol_unit"))
        self.act_vol_unit.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.act_vol_unit, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.calibration_tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.act_rot_unit = QtGui.QComboBox(self.calibration_tab)
        self.act_rot_unit.setObjectName(_fromUtf8("act_rot_unit"))
        self.act_rot_unit.addItem(_fromUtf8(""))
        self.act_rot_unit.addItem(_fromUtf8(""))
        self.act_rot_unit.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.act_rot_unit, 1, 1, 1, 1)
        self.act_vol_num = QtGui.QLineEdit(self.calibration_tab)
        self.act_vol_num.setObjectName(_fromUtf8("act_vol_num"))
        self.gridLayout_6.addWidget(self.act_vol_num, 0, 2, 1, 1)
        self.act_rot_num = QtGui.QLineEdit(self.calibration_tab)
        self.act_rot_num.setObjectName(_fromUtf8("act_rot_num"))
        self.gridLayout_6.addWidget(self.act_rot_num, 1, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cal_by_rot_radio = QtGui.QRadioButton(self.calibration_tab)
        self.cal_by_rot_radio.setText(_fromUtf8(""))
        self.cal_by_rot_radio.setObjectName(_fromUtf8("cal_by_rot_radio"))
        self.gridLayout_3.addWidget(self.cal_by_rot_radio, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.calibration_tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 1, 1, 1)
        self.cal_by_vol_unit = QtGui.QComboBox(self.calibration_tab)
        self.cal_by_vol_unit.setObjectName(_fromUtf8("cal_by_vol_unit"))
        self.cal_by_vol_unit.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cal_by_vol_unit, 0, 2, 1, 1)
        self.cal_by_vol_radio = QtGui.QRadioButton(self.calibration_tab)
        self.cal_by_vol_radio.setText(_fromUtf8(""))
        self.cal_by_vol_radio.setObjectName(_fromUtf8("cal_by_vol_radio"))
        self.gridLayout_3.addWidget(self.cal_by_vol_radio, 0, 0, 1, 1)
        self.cal_by_rot_unit = QtGui.QComboBox(self.calibration_tab)
        self.cal_by_rot_unit.setObjectName(_fromUtf8("cal_by_rot_unit"))
        self.cal_by_rot_unit.addItem(_fromUtf8(""))
        self.cal_by_rot_unit.addItem(_fromUtf8(""))
        self.cal_by_rot_unit.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cal_by_rot_unit, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.calibration_tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1)
        self.cal_by_vol_num = QtGui.QLineEdit(self.calibration_tab)
        self.cal_by_vol_num.setObjectName(_fromUtf8("cal_by_vol_num"))
        self.gridLayout_3.addWidget(self.cal_by_vol_num, 0, 3, 1, 1)
        self.cal_by_rot_num = QtGui.QLineEdit(self.calibration_tab)
        self.cal_by_rot_num.setObjectName(_fromUtf8("cal_by_rot_num"))
        self.gridLayout_3.addWidget(self.cal_by_rot_num, 1, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_7)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.calibrate_pump_button = QtGui.QPushButton(self.calibration_tab)
        self.calibrate_pump_button.setObjectName(_fromUtf8("calibrate_pump_button"))
        self.horizontalLayout_3.addWidget(self.calibrate_pump_button)
        self.calibrate_button = QtGui.QPushButton(self.calibration_tab)
        self.calibrate_button.setObjectName(_fromUtf8("calibrate_button"))
        self.horizontalLayout_3.addWidget(self.calibrate_button)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.calibration_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.command_and_stop_pane = QtGui.QWidget(self.centralwidget)
        self.command_and_stop_pane.setMinimumSize(QtCore.QSize(0, 64))
        self.command_and_stop_pane.setObjectName(_fromUtf8("command_and_stop_pane"))
        self.gridLayout_8 = QtGui.QGridLayout(self.command_and_stop_pane)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.console = QtGui.QPlainTextEdit(self.command_and_stop_pane)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.console.setPalette(palette)
        self.console.setPlainText(_fromUtf8(""))
        self.console.setBackgroundVisible(False)
        self.console.setObjectName(_fromUtf8("console"))
        self.verticalLayout_5.addWidget(self.console)
        self.gridLayout_8.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.RUN = QtGui.QPushButton(self.command_and_stop_pane)
        self.RUN.setObjectName(_fromUtf8("RUN"))
        self.verticalLayout_6.addWidget(self.RUN)
        self.STOP = QtGui.QPushButton(self.command_and_stop_pane)
        self.STOP.setObjectName(_fromUtf8("STOP"))
        self.verticalLayout_6.addWidget(self.STOP)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.command_and_stop_pane)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_2.setText(_translate("MainWindow", "Time", None))
        self.injection_vol_unit.setItemText(0, _translate("MainWindow", "cc", None))
        self.injection_vol_unit.setItemText(1, _translate("MainWindow", "mL", None))
        self.injection_vol_unit.setItemText(2, _translate("MainWindow", "L", None))
        self.injection_vol_unit.setItemText(3, _translate("MainWindow", "Gallons", None))
        self.injection_vol_unit.setItemText(4, _translate("MainWindow", "Pints", None))
        self.injection_vol_unit.setItemText(5, _translate("MainWindow", "teaspoons", None))
        self.injection_vol_unit.setItemText(6, _translate("MainWindow", "Buckets", None))
        self.injection_time_unit.setItemText(0, _translate("MainWindow", "seconds", None))
        self.injection_time_unit.setItemText(1, _translate("MainWindow", "minutes", None))
        self.injection_time_unit.setItemText(2, _translate("MainWindow", "hours", None))
        self.label.setText(_translate("MainWindow", "Amount:", None))
        self.inject_button.setText(_translate("MainWindow", "Inject", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.injection_tab), _translate("MainWindow", "Injection", None))
        self.pumping_vol_unit.setItemText(0, _translate("MainWindow", "mL", None))
        self.pumping_Q_unit.setItemText(0, _translate("MainWindow", "mL/s", None))
        self.label_3.setText(_translate("MainWindow", "Q(volumetric flow rate)", None))
        self.label_5.setText(_translate("MainWindow", "volume", None))
        self.label_7.setText(_translate("MainWindow", "Top wait time", None))
        self.label_9.setText(_translate("MainWindow", "Push time", None))
        self.label_8.setText(_translate("MainWindow", "Bottom wait time", None))
        self.label_4.setText(_translate("MainWindow", "Pull time", None))
        self.pumping_pull_time_unit.setItemText(0, _translate("MainWindow", "seconds", None))
        self.pumping_pull_time_unit.setItemText(1, _translate("MainWindow", "minutes", None))
        self.pumping_pull_time_unit.setItemText(2, _translate("MainWindow", "hours", None))
        self.pumping_pumps_unit.setItemText(0, _translate("MainWindow", "num", None))
        self.pumping_pumps_unit.setItemText(1, _translate("MainWindow", "K", None))
        self.pumping_pumps_unit.setItemText(2, _translate("MainWindow", "M", None))
        self.pumping_top_wait_time_unit.setItemText(0, _translate("MainWindow", "seconds", None))
        self.pumping_top_wait_time_unit.setItemText(1, _translate("MainWindow", "minutes", None))
        self.pumping_top_wait_time_unit.setItemText(2, _translate("MainWindow", "hours", None))
        self.pumping_push_time_unit.setItemText(0, _translate("MainWindow", "seconds", None))
        self.pumping_push_time_unit.setItemText(1, _translate("MainWindow", "minutes", None))
        self.pumping_push_time_unit.setItemText(2, _translate("MainWindow", "hours", None))
        self.pumping_bottom_wait_time_unit.setItemText(0, _translate("MainWindow", "seconds", None))
        self.pumping_bottom_wait_time_unit.setItemText(1, _translate("MainWindow", "minutes", None))
        self.pumping_bottom_wait_time_unit.setItemText(2, _translate("MainWindow", "hours", None))
        self.label_10.setText(_translate("MainWindow", "No. of pumps", None))
        self.pumping_total_time_unit.setItemText(0, _translate("MainWindow", "seconds", None))
        self.pumping_total_time_unit.setItemText(1, _translate("MainWindow", "minutes", None))
        self.pumping_total_time_unit.setItemText(2, _translate("MainWindow", "hours", None))
        self.label_6.setText(_translate("MainWindow", "Total time", None))
        self.pump_button.setText(_translate("MainWindow", "Pump", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pumpin_tab), _translate("MainWindow", "Pumping", None))
        self.label_13.setText(_translate("MainWindow", "Actual volume", None))
        self.act_vol_unit.setItemText(0, _translate("MainWindow", "mL", None))
        self.label_14.setText(_translate("MainWindow", "Actual rotations", None))
        self.act_rot_unit.setItemText(0, _translate("MainWindow", "°", None))
        self.act_rot_unit.setItemText(1, _translate("MainWindow", "θ", None))
        self.act_rot_unit.setItemText(2, _translate("MainWindow", "no. rev.", None))
        self.label_12.setText(_translate("MainWindow", "Rotations", None))
        self.cal_by_vol_unit.setItemText(0, _translate("MainWindow", "mL", None))
        self.cal_by_rot_unit.setItemText(0, _translate("MainWindow", "°", None))
        self.cal_by_rot_unit.setItemText(1, _translate("MainWindow", "θ", None))
        self.cal_by_rot_unit.setItemText(2, _translate("MainWindow", "no. rev.", None))
        self.label_11.setText(_translate("MainWindow", "Test volume", None))
        self.calibrate_pump_button.setText(_translate("MainWindow", "Pump", None))
        self.calibrate_button.setText(_translate("MainWindow", "Calibrate", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibration_tab), _translate("MainWindow", "Calibration", None))
        self.RUN.setText(_translate("MainWindow", "RUN", None))
        self.STOP.setText(_translate("MainWindow", "STOP", None))

