# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syringe_pump_controller_ui.ui'
#
# Created: Wed Nov 19 15:45:12 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.connection_tab = QtWidgets.QWidget()
        self.connection_tab.setObjectName("connection_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.connection_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.connection_tab)
        self.label_8.setScaledContents(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.baud_select = QtWidgets.QComboBox(self.connection_tab)
        self.baud_select.setMinimumSize(QtCore.QSize(128, 0))
        self.baud_select.setObjectName("baud_select")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.baud_select.addItem("")
        self.gridLayout_2.addWidget(self.baud_select, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.connection_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.port_select = QtWidgets.QComboBox(self.connection_tab)
        self.port_select.setMinimumSize(QtCore.QSize(128, 0))
        self.port_select.setObjectName("port_select")
        self.gridLayout_2.addWidget(self.port_select, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.connection_tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.portscan_button = QtWidgets.QPushButton(self.connection_tab)
        self.portscan_button.setObjectName("portscan_button")
        self.gridLayout_2.addWidget(self.portscan_button, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.connection_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.pump_select = QtWidgets.QComboBox(self.connection_tab)
        self.pump_select.setMinimumSize(QtCore.QSize(128, 0))
        self.pump_select.setObjectName("pump_select")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.pump_select.addItem("")
        self.gridLayout_2.addWidget(self.pump_select, 2, 2, 1, 1)
        self.pumpnew_button = QtWidgets.QPushButton(self.connection_tab)
        self.pumpnew_button.setObjectName("pumpnew_button")
        self.gridLayout_2.addWidget(self.pumpnew_button, 2, 3, 1, 1)
        self.pumpswitch_button = QtWidgets.QPushButton(self.connection_tab)
        self.pumpswitch_button.setObjectName("pumpswitch_button")
        self.gridLayout_2.addWidget(self.pumpswitch_button, 2, 4, 1, 1)
        self.pumpdelete_button = QtWidgets.QPushButton(self.connection_tab)
        self.pumpdelete_button.setObjectName("pumpdelete_button")
        self.gridLayout_2.addWidget(self.pumpdelete_button, 2, 5, 1, 1)
        self.pump_exists = QtWidgets.QLabel(self.connection_tab)
        self.pump_exists.setObjectName("pump_exists")
        self.gridLayout_2.addWidget(self.pump_exists, 2, 7, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.RUN = QtWidgets.QPushButton(self.connection_tab)
        self.RUN.setObjectName("RUN")
        self.horizontalLayout_2.addWidget(self.RUN)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.connection_tab, "")
        self.Injection_tab = QtWidgets.QWidget()
        self.Injection_tab.setObjectName("Injection_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Injection_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.Injection_tab)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_23 = QtWidgets.QLabel(self.Injection_tab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.Injection_tab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 1, 0, 1, 1)
        self.max_inject_i = QtWidgets.QLabel(self.Injection_tab)
        self.max_inject_i.setEnabled(True)
        self.max_inject_i.setMinimumSize(QtCore.QSize(128, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.max_inject_i.setPalette(palette)
        self.max_inject_i.setObjectName("max_inject_i")
        self.gridLayout_8.addWidget(self.max_inject_i, 0, 1, 1, 1)
        self.max_draw_i = QtWidgets.QLabel(self.Injection_tab)
        self.max_draw_i.setMinimumSize(QtCore.QSize(128, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.max_draw_i.setPalette(palette)
        self.max_draw_i.setObjectName("max_draw_i")
        self.gridLayout_8.addWidget(self.max_draw_i, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 0, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_8)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_27 = QtWidgets.QLabel(self.Injection_tab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 0, 0, 1, 1)
        self.inject_amount_num = QtWidgets.QLineEdit(self.Injection_tab)
        self.inject_amount_num.setMinimumSize(QtCore.QSize(128, 0))
        self.inject_amount_num.setObjectName("inject_amount_num")
        self.gridLayout_9.addWidget(self.inject_amount_num, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.Injection_tab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 0, 2, 1, 1)
        self.inject_time_num = QtWidgets.QLineEdit(self.Injection_tab)
        self.inject_time_num.setMinimumSize(QtCore.QSize(128, 0))
        self.inject_time_num.setObjectName("inject_time_num")
        self.gridLayout_9.addWidget(self.inject_time_num, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.inject_button = QtWidgets.QPushButton(self.Injection_tab)
        self.inject_button.setObjectName("inject_button")
        self.horizontalLayout_9.addWidget(self.inject_button)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.Injection_tab, "")
        self.Pumping_tab = QtWidgets.QWidget()
        self.Pumping_tab.setObjectName("Pumping_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Pumping_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.max_draw_p = QtWidgets.QLabel(self.Pumping_tab)
        self.max_draw_p.setMinimumSize(QtCore.QSize(128, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.max_draw_p.setPalette(palette)
        self.max_draw_p.setObjectName("max_draw_p")
        self.horizontalLayout_6.addWidget(self.max_draw_p)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_17 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.pumping_vol_num = QtWidgets.QLineEdit(self.Pumping_tab)
        self.pumping_vol_num.setObjectName("pumping_vol_num")
        self.gridLayout_5.addWidget(self.pumping_vol_num, 0, 1, 1, 1)
        self.pumping_pumps_num = QtWidgets.QLineEdit(self.Pumping_tab)
        self.pumping_pumps_num.setObjectName("pumping_pumps_num")
        self.gridLayout_5.addWidget(self.pumping_pumps_num, 1, 1, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_18 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.pumping_push_time_num = QtWidgets.QLineEdit(self.Pumping_tab)
        self.pumping_push_time_num.setObjectName("pumping_push_time_num")
        self.gridLayout_6.addWidget(self.pumping_push_time_num, 2, 1, 1, 1)
        self.pumping_bottom_wait_time_num = QtWidgets.QLineEdit(self.Pumping_tab)
        self.pumping_bottom_wait_time_num.setObjectName("pumping_bottom_wait_time_num")
        self.gridLayout_6.addWidget(self.pumping_bottom_wait_time_num, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 2, 0, 1, 1)
        self.pumping_pull_time_num = QtWidgets.QLineEdit(self.Pumping_tab)
        self.pumping_pull_time_num.setObjectName("pumping_pull_time_num")
        self.gridLayout_6.addWidget(self.pumping_pull_time_num, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 3, 0, 1, 1)
        self.pumping_top_wait_time_num = QtWidgets.QLineEdit(self.Pumping_tab)
        self.pumping_top_wait_time_num.setObjectName("pumping_top_wait_time_num")
        self.gridLayout_6.addWidget(self.pumping_top_wait_time_num, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.Pumping_tab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem14)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.pump_button = QtWidgets.QPushButton(self.Pumping_tab)
        self.pump_button.setObjectName("pump_button")
        self.horizontalLayout_8.addWidget(self.pump_button)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.Pumping_tab, "")
        self.Calibration_tab = QtWidgets.QWidget()
        self.Calibration_tab.setObjectName("Calibration_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Calibration_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.Calibration_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.max_inject_c = QtWidgets.QLabel(self.Calibration_tab)
        self.max_inject_c.setMinimumSize(QtCore.QSize(128, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.max_inject_c.setPalette(palette)
        self.max_inject_c.setTextFormat(QtCore.Qt.AutoText)
        self.max_inject_c.setObjectName("max_inject_c")
        self.gridLayout_4.addWidget(self.max_inject_c, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.Calibration_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.max_draw_c = QtWidgets.QLabel(self.Calibration_tab)
        self.max_draw_c.setMinimumSize(QtCore.QSize(128, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.max_draw_c.setPalette(palette)
        self.max_draw_c.setObjectName("max_draw_c")
        self.gridLayout_4.addWidget(self.max_draw_c, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.Calibration_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.calib_pos_per_rad_line = QtWidgets.QLabel(self.Calibration_tab)
        self.calib_pos_per_rad_line.setMinimumSize(QtCore.QSize(128, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.calib_pos_per_rad_line.setPalette(palette)
        self.calib_pos_per_rad_line.setObjectName("calib_pos_per_rad_line")
        self.gridLayout_3.addWidget(self.calib_pos_per_rad_line, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.Calibration_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.calib_ml_per_rad_line = QtWidgets.QLabel(self.Calibration_tab)
        self.calib_ml_per_rad_line.setMinimumSize(QtCore.QSize(128, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.calib_ml_per_rad_line.setPalette(palette)
        self.calib_ml_per_rad_line.setObjectName("calib_ml_per_rad_line")
        self.gridLayout_3.addWidget(self.calib_ml_per_rad_line, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.calib_default_radio = QtWidgets.QCheckBox(self.Calibration_tab)
        self.calib_default_radio.setObjectName("calib_default_radio")
        self.horizontalLayout_3.addWidget(self.calib_default_radio)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem18)
        self.hbox214 = QtWidgets.QHBoxLayout()
        self.hbox214.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hbox214.setObjectName("hbox214")
        self.label_9 = QtWidgets.QLabel(self.Calibration_tab)
        self.label_9.setObjectName("label_9")
        self.hbox214.addWidget(self.label_9)
        self.cal_expected_line = QtWidgets.QLineEdit(self.Calibration_tab)
        self.cal_expected_line.setObjectName("cal_expected_line")
        self.hbox214.addWidget(self.cal_expected_line)
        self.cal_expect_unit = QtWidgets.QComboBox(self.Calibration_tab)
        self.cal_expect_unit.setObjectName("cal_expect_unit")
        self.cal_expect_unit.addItem("")
        self.cal_expect_unit.addItem("")
        self.cal_expect_unit.addItem("")
        self.cal_expect_unit.addItem("")
        self.hbox214.addWidget(self.cal_expect_unit)
        self.label_10 = QtWidgets.QLabel(self.Calibration_tab)
        self.label_10.setObjectName("label_10")
        self.hbox214.addWidget(self.label_10)
        self.cal_result_line = QtWidgets.QLineEdit(self.Calibration_tab)
        self.cal_result_line.setObjectName("cal_result_line")
        self.hbox214.addWidget(self.cal_result_line)
        self.cal_expect_unit_label = QtWidgets.QLabel(self.Calibration_tab)
        self.cal_expect_unit_label.setMinimumSize(QtCore.QSize(96, 0))
        self.cal_expect_unit_label.setObjectName("cal_expect_unit_label")
        self.hbox214.addWidget(self.cal_expect_unit_label)
        self.verticalLayout_4.addLayout(self.hbox214)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem19)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem20)
        self.calibrate_button = QtWidgets.QPushButton(self.Calibration_tab)
        self.calibrate_button.setObjectName("calibrate_button")
        self.horizontalLayout_5.addWidget(self.calibrate_button)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.Calibration_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.console = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.console.setMaximumSize(QtCore.QSize(16777215, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.console.setPalette(palette)
        self.console.setObjectName("console")
        self.horizontalLayout.addWidget(self.console)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_velocity_button = QtWidgets.QPushButton(self.centralwidget)
        self.check_velocity_button.setObjectName("check_velocity_button")
        self.verticalLayout_2.addWidget(self.check_velocity_button)
        self.check_status_button = QtWidgets.QPushButton(self.centralwidget)
        self.check_status_button.setObjectName("check_status_button")
        self.verticalLayout_2.addWidget(self.check_status_button)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.STOP = QtWidgets.QPushButton(self.centralwidget)
        self.STOP.setObjectName("STOP")
        self.verticalLayout_3.addWidget(self.STOP)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.set_min_button = QtWidgets.QCheckBox(self.centralwidget)
        self.set_min_button.setObjectName("set_min_button")
        self.gridLayout.addWidget(self.set_min_button, 0, 0, 1, 1)
        self.no_min_button = QtWidgets.QCheckBox(self.centralwidget)
        self.no_min_button.setObjectName("no_min_button")
        self.gridLayout.addWidget(self.no_min_button, 0, 1, 1, 1)
        self.set_max_button = QtWidgets.QCheckBox(self.centralwidget)
        self.set_max_button.setObjectName("set_max_button")
        self.gridLayout.addWidget(self.set_max_button, 1, 0, 1, 1)
        self.no_max_button = QtWidgets.QCheckBox(self.centralwidget)
        self.no_max_button.setObjectName("no_max_button")
        self.gridLayout.addWidget(self.no_max_button, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CES Syringe Pump Version 0.9.2 Alpha"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#aa0000;\">Not Connected</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Warning: When you initialize the motor, it will spin a few revolutions. Please make sure that you have room for this."))
        self.baud_select.setItemText(0, _translate("MainWindow", "9600"))
        self.baud_select.setItemText(1, _translate("MainWindow", "19200"))
        self.baud_select.setItemText(2, _translate("MainWindow", "38400"))
        self.label_2.setText(_translate("MainWindow", "Baud:"))
        self.label.setText(_translate("MainWindow", "Port:"))
        self.portscan_button.setText(_translate("MainWindow", "Scan"))
        self.label_5.setText(_translate("MainWindow", "Address:"))
        self.pump_select.setItemText(0, _translate("MainWindow", "Pump 1"))
        self.pump_select.setItemText(1, _translate("MainWindow", "Pump 2"))
        self.pump_select.setItemText(2, _translate("MainWindow", "Pump 3"))
        self.pump_select.setItemText(3, _translate("MainWindow", "Pump 4"))
        self.pump_select.setItemText(4, _translate("MainWindow", "Pump 5"))
        self.pump_select.setItemText(5, _translate("MainWindow", "Pump 6"))
        self.pump_select.setItemText(6, _translate("MainWindow", "Pump 7"))
        self.pump_select.setItemText(7, _translate("MainWindow", "Pump 8"))
        self.pump_select.setItemText(8, _translate("MainWindow", "Pump 9"))
        self.pump_select.setItemText(9, _translate("MainWindow", "Pump A"))
        self.pump_select.setItemText(10, _translate("MainWindow", "Pump B"))
        self.pump_select.setItemText(11, _translate("MainWindow", "Pump C"))
        self.pump_select.setItemText(12, _translate("MainWindow", "Pump D"))
        self.pump_select.setItemText(13, _translate("MainWindow", "Pump E"))
        self.pump_select.setItemText(14, _translate("MainWindow", "Pump F"))
        self.pump_select.setItemText(15, _translate("MainWindow", "Pump 0"))
        self.pumpnew_button.setText(_translate("MainWindow", "New"))
        self.pumpswitch_button.setText(_translate("MainWindow", "Switch To"))
        self.pumpdelete_button.setText(_translate("MainWindow", "Delete"))
        self.pump_exists.setText(_translate("MainWindow", "Exists"))
        self.RUN.setText(_translate("MainWindow", "INITIALIZE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connection_tab), _translate("MainWindow", "Connection"))
        self.label_22.setText(_translate("MainWindow", "Positive volumes will inject, negative volumes will draw."))
        self.label_23.setText(_translate("MainWindow", "Max Inject (mL):"))
        self.label_24.setText(_translate("MainWindow", "Max Draw (mL);"))
        self.max_inject_i.setText(_translate("MainWindow", "NA"))
        self.max_draw_i.setText(_translate("MainWindow", "NA"))
        self.label_27.setText(_translate("MainWindow", "Volume (mL):"))
        self.label_28.setText(_translate("MainWindow", "Time (s):"))
        self.inject_button.setText(_translate("MainWindow", "Inject"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Injection_tab), _translate("MainWindow", "Injection"))
        self.label_12.setText(_translate("MainWindow", "Stroke volume indicates both volume drawn and injected. (e.g. 3mL will draw 3mL, then inject 3mL, then repeat.)"))
        self.label_13.setText(_translate("MainWindow", "Set no. of strokes to 0 to loop infinitely"))
        self.label_14.setText(_translate("MainWindow", "Max Draw (mL):"))
        self.max_draw_p.setText(_translate("MainWindow", "NA"))
        self.label_17.setText(_translate("MainWindow", "No. Of Strokes (num):"))
        self.label_16.setText(_translate("MainWindow", "Stroke Volume (mL):"))
        self.label_18.setText(_translate("MainWindow", "Pull Time (s):"))
        self.label_20.setText(_translate("MainWindow", "Push Time (s):"))
        self.label_21.setText(_translate("MainWindow", "Bottom Wait Time (s):"))
        self.label_19.setText(_translate("MainWindow", "Top Wait Time (s):"))
        self.pump_button.setText(_translate("MainWindow", "Pump"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Pumping_tab), _translate("MainWindow", "Pumping"))
        self.label_6.setText(_translate("MainWindow", "Max Inject (mL):"))
        self.max_inject_c.setText(_translate("MainWindow", "NA"))
        self.label_7.setText(_translate("MainWindow", "Max Draw (mL):"))
        self.max_draw_c.setText(_translate("MainWindow", "NA"))
        self.label_3.setText(_translate("MainWindow", "mL/rad"))
        self.calib_pos_per_rad_line.setText(_translate("MainWindow", "NA"))
        self.label_4.setText(_translate("MainWindow", "motor pos/rad"))
        self.calib_ml_per_rad_line.setText(_translate("MainWindow", "NA"))
        self.calib_default_radio.setText(_translate("MainWindow", "Default?"))
        self.label_9.setText(_translate("MainWindow", "Expected:"))
        self.cal_expect_unit.setItemText(0, _translate("MainWindow", "mL"))
        self.cal_expect_unit.setItemText(1, _translate("MainWindow", "Rotations"))
        self.cal_expect_unit.setItemText(2, _translate("MainWindow", "Radians"))
        self.cal_expect_unit.setItemText(3, _translate("MainWindow", "Degrees"))
        self.label_10.setText(_translate("MainWindow", "Result:"))
        self.cal_expect_unit_label.setText(_translate("MainWindow", "mL"))
        self.calibrate_button.setText(_translate("MainWindow", "Calibrate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Calibration_tab), _translate("MainWindow", "Calibration"))
        self.check_velocity_button.setText(_translate("MainWindow", "Check Velocity"))
        self.check_status_button.setText(_translate("MainWindow", "Check Status"))
        self.STOP.setText(_translate("MainWindow", "STOP"))
        self.set_min_button.setText(_translate("MainWindow", "Set Max Inject"))
        self.no_min_button.setText(_translate("MainWindow", "No Max Inject"))
        self.set_max_button.setText(_translate("MainWindow", "Set Max Draw"))
        self.no_max_button.setText(_translate("MainWindow", "No Max Draw"))

